// Aperçu interactif : vrais composants, données fictives, aucun Supabase ni push.
import fs from 'node:fs'
import path from 'node:path'
import http from 'node:http'
import { createRequire } from 'node:module'
const require = createRequire(import.meta.url), root = process.cwd(), dir = path.join(root, 'out/celebrations-preview')
fs.mkdirSync(dir, { recursive: true })
fs.writeFileSync(path.join(dir, 'loader.cjs'), `const ts=require('typescript');module.exports=source=>ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText`)
fs.writeFileSync(path.join(dir, 'navigation.js'), `import React,{useSyncExternalStore} from 'react';let version=0;const listeners=new Set();const change=url=>{history.pushState(null,'',url);version++;listeners.forEach(fn=>fn())};const tick=()=>useSyncExternalStore(fn=>{listeners.add(fn);return()=>listeners.delete(fn)},()=>version);export const useSearchParams=()=>{tick();return new URLSearchParams(location.search)};export const usePathname=()=>{tick();return location.pathname};export const useRouter=()=>({push:change,replace:change});`)
fs.writeFileSync(path.join(dir, 'link.js'), `import React from 'react';export default function Link({children,...props}){return React.createElement('a',props,children)}`)
fs.writeFileSync(path.join(dir, 'entry.js'), String.raw`
import React,{useState} from 'react';import {createRoot} from 'react-dom/client';import ShareImageButton from '../../components/ShareImageButton';import ContactDraftProvider from '../../components/ContactDraftProvider';import MainSpaces from '../../components/MainSpaces';import ClosePeopleNav from '../../components/ClosePeopleNav';import CalendarExperience from '../../components/CalendarExperience';import {contactImageFields} from '../../lib/image-projections';import {DEFAULT_AVATAR_V3} from '../../lib/avatar-collection-v3';
const contact={prenom:'Camille',nom:'Martin',date_naissance:'1990-10-10',email:'PRIVE_MAIL@example.invalid',telephone_numero:'PRIVE_PHONE',note:'NOTE_PRIVEE',user_id:'PRIVE_OWNER'};
const snapshot={format:2,renderVersion:2,templateVersion:1,templateId:'clair_de_lune',message:'Joyeux anniversaire !\nQue cette journée soit aussi belle que les moments partagés sous les étoiles.',signature:'Lune',avatar:DEFAULT_AVATAR_V3};
function App(){const[view,setView]=useState('cards'),[month,setMonth]=useState('2026-10'),[theme,setTheme]=useState('dark');return React.createElement(ContactDraftProvider,null,React.createElement('div',{className:'mx-auto max-w-6xl space-y-5 px-3 pb-24 text-ink'},React.createElement('p',null,'Recette fictive : aucune sauvegarde, aucun push'),React.createElement('div',{className:'flex gap-2'},React.createElement('button',{onClick:()=>setView(view==='cards'?'calendar':'cards'),className:'min-h-11 rounded-xl border px-3'},'Changer de vue'),React.createElement('button',{onClick:()=>{setTheme(theme==='dark'?'light':'dark');document.documentElement.dataset.theme=theme==='dark'?'light':'dark'},className:'min-h-11 rounded-xl border px-3'},'Thème')),React.createElement(MainSpaces),React.createElement(ClosePeopleNav),view==='cards'?React.createElement('main',{className:'space-y-6'},React.createElement('section',{className:'rounded-xl border p-4'},React.createElement('h1',null,'Carte personnelle'),React.createElement(ShareImageButton,{title:'Ma carte',snapshot,label:'Exporter la carte personnelle'})),React.createElement('section',{className:'rounded-xl border p-4'},React.createElement('h2',null,'Fiche Camille'),React.createElement(ShareImageButton,{title:'Fiche contact',fields:contactImageFields(contact),label:'Exporter le contact'})),React.createElement('section',{className:'rounded-xl border p-4'},React.createElement('h2',null,'Texte long'),React.createElement(ShareImageButton,{title:'Tous les souvenirs',fields:[{id:'text',label:'Souvenirs',value:Array.from({length:170},(_,i)=>'Souvenir '+String(i).padStart(3,'0')+' : une promenade, des étoiles et de belles rencontres.').join('\n')}],label:'Exporter le texte long'}))):React.createElement(CalendarExperience,{month,onMonthChange:setMonth,views:[{key:'birthday',date:'2026-10-10',kind:'anniversaire',title:'Anniversaire de Camille',contact:{id:1,...contact},age:36,reminder:true,event:null,occurrence:null}],contactIds:null,listSelector:null,manageDates:null}))) };createRoot(document.getElementById('root')).render(React.createElement(App));
`)
const webpack = require('next/dist/compiled/webpack/webpack').webpack
webpack({ mode:'development',entry:path.join(dir,'entry.js'),output:{path:dir,filename:'bundle.js'},resolve:{extensions:['.tsx','.ts','.js'],alias:{'@':root}},module:{rules:[{test:/\.tsx?$/,exclude:/node_modules/,use:path.join(dir,'loader.cjs')}]},devtool:false,
plugins:[new webpack.DefinePlugin({'process.env':JSON.stringify({NODE_ENV:'development'})}),new webpack.NormalModuleReplacementPlugin(/^next\/link$|^next\/navigation$/, resource=>{resource.request=path.join(dir,resource.request==='next/link'?'link.js':'navigation.js')})]},async(error,stats)=>{
 if(error||stats.hasErrors()){console.error(error||stats.toString({all:false,errors:true}));process.exitCode=1;return}
 const css=await require('postcss')([require('@tailwindcss/postcss')()]).process(fs.readFileSync(path.join(root,'app/globals.css'),'utf8'),{from:path.join(root,'app/globals.css')});fs.writeFileSync(path.join(dir,'style.css'),css.css)
 const html='<!doctype html><html lang="fr" data-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Recette célébrations</title><link rel="stylesheet" href="/style.css"></head><body style="margin:0;font-family:system-ui"><div id="root"></div><script src="/bundle.js"></script></body></html>'
 http.createServer((req,res)=>{const pathname=new URL(req.url,'http://127.0.0.1:3217').pathname;const file=pathname.startsWith('/')&&!pathname.includes('..')?path.join(dir,pathname.slice(1)):'';const asset=fs.existsSync(file)&&fs.statSync(file).isFile();res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type',asset?(file.endsWith('.css')?'text/css':file.endsWith('.js')?'text/javascript':'application/octet-stream'):'text/html; charset=utf-8');res.end(asset?fs.readFileSync(file):html)}).listen(3217,'127.0.0.1',()=>console.log('PREVIEW_READY http://127.0.0.1:3217'))
})
