// Recette des vrais composants/styles : comptes fictifs, données en mémoire, réseau externe interdit.
// node tests/etoiles-preview.mjs — http://127.0.0.1:3210
import fs from 'node:fs'
import path from 'node:path'
import http from 'node:http'
import { createRequire } from 'node:module'
const require=createRequire(import.meta.url),root=process.cwd(),dir=path.join(root,'out/etoiles-preview')
fs.mkdirSync(dir,{recursive:true})
fs.writeFileSync(path.join(dir,'link.js'),`import React from 'react';export default function Link({children,...props}){return React.createElement('a',{...props,onClick:e=>{e.preventDefault();history.pushState({},'',props.href);window.dispatchEvent(new PopStateEvent('popstate'))}},children)}`)
fs.writeFileSync(path.join(dir,'navigation.js'),`import {useState,useEffect} from 'react';export function usePathname(){const[path,set]=useState(location.pathname);useEffect(()=>{const f=()=>set(location.pathname);window.addEventListener('popstate',f);return()=>window.removeEventListener('popstate',f)},[]);return path}export function useRouter(){return {push(path){history.pushState({},'',path);window.dispatchEvent(new PopStateEvent('popstate'))},replace(path){history.replaceState({},'',path);window.dispatchEvent(new PopStateEvent('popstate'))},refresh(){}}}`)
fs.writeFileSync(path.join(dir,'store.js'),`
export const A='10000000-0000-4000-8000-000000000001',B='10000000-0000-4000-8000-000000000002',C='10000000-0000-4000-8000-000000000003',R='20000000-0000-4000-8000-000000000001',D='2026-10-09T10:00:00Z',E='2026-10-16T10:00:00Z',TOKEN='a'.repeat(42)+'A';
export const state={stars:[{id:R,etoile_id:B,identite:'Camille',origine:'demande',created_at:D,revision:1}],incoming:[{id:'20000000-0000-4000-8000-000000000002',auteur_id:C,identite:'Alexandre avec un prénom suffisamment long',created_at:D,expires_at:E}],sent:[],blocked:[],links:[],associations:[],contacts:[{id:4,user_id:A,prenom:'Camille',nom:'Exemple',email:'camille@example.invalid',relation:'ami',est_favori:false}],notifications:[{id:R,user_id:A,message:'Un rappel fictif',lue:false,type:'anniversaire',created_at:D,contact_id:4,jours_restants:7,event_date:D}],notifications_etoiles:[{id:R,user_id:A,type:'demande_etoile',lue:false,created_at:D}]};
export const copy=value=>JSON.parse(JSON.stringify(value));
`)
fs.writeFileSync(path.join(dir,'data.js'),`
import {state,A,B,R,D,E,TOKEN,copy} from './store';export class EtoilesRequestError extends Error{constructor(message,status=0){super(message);this.status=status}}
const operations=new Map();export async function recogniseEtoiles(){};
export async function readEtoiles(owner,view){if(owner!==A)return [];return copy(({actives:state.stars,recues:state.incoming,envoyees:state.sent,bloquees:state.blocked,liens:state.links,associations:state.associations})[view])}
export async function sendEtoileCommand(owner,command){if(operations.has(command.operation))return copy(operations.get(command.operation));if(window.failNext){window.failNext=false;throw new EtoilesRequestError('Panne réseau fictive : ta saisie reste disponible.',503)}
const{action,donnees:data}=command;let result={ok:true};
if(action.startsWith('demander')){state.sent.push({id:crypto.randomUUID(),adresse_cible:data.email??'adresse@example.invalid',etat:'en_attente',created_at:D,expires_at:E});result.message='Demande enregistrée.'}
if(action==='accepter'){const d=state.incoming.find(d=>d.id===data.demandeId);if(d)state.stars.push({id:d.id,etoile_id:d.auteur_id,identite:d.identite,origine:'demande',created_at:D,revision:1});state.incoming=state.incoming.filter(d=>d.id!==data.demandeId);result.relationId=data.demandeId}
if(action==='refuser')state.incoming=state.incoming.filter(d=>d.id!==data.demandeId);
if(action==='annuler')state.sent=state.sent.map(d=>d.id===data.demandeId?{...d,etat:'annulee'}:d);
if(action==='retirer'||action==='bloquer'){state.stars=state.stars.filter(d=>d.etoile_id!==data.etoileId);state.incoming=state.incoming.filter(d=>d.auteur_id!==data.etoileId);if(action==='bloquer')state.blocked.push({id:data.etoileId,created_at:D})}
if(action==='debloquer')state.blocked=state.blocked.filter(d=>d.id!==data.etoileId);
if(action==='associer_contact'){state.associations=state.associations.filter(d=>d.contact_id!==data.contactId);state.associations.push({contact_id:data.contactId,etoile_id:data.etoileId,relation_id:state.stars.find(s=>s.etoile_id===data.etoileId)?.id??R})}
if(action==='creer_lien'){result={ok:true,lienId:crypto.randomUUID(),expiresAt:E};state.links.push({id:result.lienId,created_at:D,expires_at:E,revoque:false})}
if(action==='revoquer_lien')state.links=state.links.map(d=>d.id===data.lienId?{...d,revoque:true}:d);
operations.set(command.operation,result);return {...result,...(action==='creer_lien'?{token:TOKEN}:{})}}
export async function exportEtoiles(){throw new Error('Export désactivé dans cet aperçu fictif')}
`)
fs.writeFileSync(path.join(dir,'supabase.js'),`
import {state,A,D,copy} from './store';export const supabase={auth:{getUser:async()=>({data:{user:{id:window.fixtureOwner??A,email_confirmed_at:D,email:'fiction@example.invalid'}},error:null}),getSession:async()=>({data:{session:{user:{id:window.fixtureOwner??A},access_token:'FAUX'}},error:null}),onAuthStateChange(){return {data:{subscription:{unsubscribe(){}}}}}},channel(){const q={on:()=>q,subscribe:()=>q};return q},removeChannel(){},from(table){let filter=[],key='id',maximum=200,mode='read',values,single=false;const q={select:()=>q,eq:(k,v)=>{filter.push(r=>r[k]===v);return q},gt:(k,v)=>{filter.push(r=>r[k]>v);return q},or:()=>{filter.push(r=>!r.lue);return q},order:k=>{key=k;return q},limit:n=>{maximum=n;return q},maybeSingle:()=>{single=true;return q},single:()=>{single=true;return q},update:v=>{mode='update';values=v;return q},delete:()=>{mode='delete';return q},insert:v=>{mode='insert';values=v;return q},then(fn){let all=state[table]??[];if(mode==='insert'){for(const value of values)all.push({id:all.length+10,...value});state[table]=all}const rows=all.filter(r=>filter.every(f=>f(r)));if(mode==='update')rows.forEach(r=>Object.assign(r,values));if(mode==='delete')state[table]=all.filter(r=>!rows.includes(r));const data=copy(rows.sort((a,b)=>a[key]<b[key]?-1:1).slice(0,maximum));return Promise.resolve({data:single?data[0]??null:data,error:null}).then(fn)}};return q}};
`)
fs.writeFileSync(path.join(dir,'loader.cjs'),`const ts=require('typescript');module.exports=source=>ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText`)
fs.writeFileSync(path.join(dir,'entry.js'),`
import React,{useState,useEffect} from 'react';import {createRoot} from 'react-dom/client';import {A,B,TOKEN} from './store';import EtoilesProvider from '../../components/etoiles/EtoilesContext';import EtoilesScreen from '../../components/etoiles/EtoilesScreen';import PublicEtoileScreen from '../../components/etoiles/PublicEtoileScreen';import Contacts from '../../app/dashboard/contacts/page';import NewContacts from '../../app/dashboard/contacts/nouveau/page';import Notifications from '../../app/dashboard/notifications/page';import NotificationBell from '../../components/NotificationBell';import {DashboardUserContext} from '../../components/DashboardUserContext';import ContactDraftProvider from '../../components/ContactDraftProvider';import {DrawerProvider} from '../../components/DrawerContext';import {usePathname,useRouter} from './navigation';
window.fetch=()=>{throw new Error('Réseau interdit dans cet aperçu')};
function App(){const[owner,setOwner]=useState(A),[dark,setDark]=useState(true),page=usePathname(),router=useRouter();window.fixtureOwner=owner;const user={id:owner,email:'fiction@example.invalid',prenom:owner===A?'Alex':'Autre compte'};
return React.createElement(DashboardUserContext.Provider,{key:owner,value:user},React.createElement(ContactDraftProvider,null,React.createElement(EtoilesProvider,null,React.createElement(DrawerProvider,null,
React.createElement('nav',{className:'flex flex-wrap items-center gap-2 border-b border-line p-3 text-ink'},React.createElement('span',{className:'w-full text-xs'},'Recette fictive en mémoire — aucune écriture distante'),...['Étoiles','Contacts','Notifications'].map((label,i)=>React.createElement('button',{key:label,className:'min-h-11 rounded-lg border border-line px-3',onClick:()=>router.push(['/dashboard/etoiles','/dashboard/contacts','/dashboard/notifications'][i])},label)),React.createElement('button',{className:'min-h-11',onClick:()=>{const next=!dark;setDark(next);document.documentElement.dataset.theme=next?'dark':'light'}},'Thème'),React.createElement('button',{className:'min-h-11',onClick:()=>setOwner(owner===A?B:A)},'Changer de compte'),React.createElement('button',{className:'min-h-11',onClick:()=>window.failNext=true},'Simuler une panne'),React.createElement('button',{className:'min-h-11',onClick:()=>router.push('/etoile#'+TOKEN)},'Entrée publique fictive'),React.createElement(NotificationBell)),
page==='/etoile'?React.createElement(PublicEtoileScreen):page==='/dashboard/contacts'?React.createElement(Contacts):page==='/dashboard/contacts/nouveau'?React.createElement(NewContacts):page==='/dashboard/notifications'?React.createElement(Notifications):React.createElement(EtoilesScreen)))))
};createRoot(document.getElementById('root')).render(React.createElement(App));
`)
const webpack=require('next/dist/compiled/webpack/webpack').webpack
webpack({mode:'development',entry:path.join(dir,'entry.js'),output:{path:dir,filename:'bundle.js'},resolve:{extensions:['.tsx','.ts','.js'],alias:{'@':root}},module:{rules:[{test:/\.tsx?$/,exclude:/node_modules/,use:path.join(dir,'loader.cjs')}]},devtool:false,
plugins:[new webpack.DefinePlugin({'process.env':JSON.stringify({NODE_ENV:'development'})}),new webpack.NormalModuleReplacementPlugin(/^next\/link$|^next\/navigation$|etoiles-data$|supabase-browser$/,resource=>{resource.request=path.join(dir,resource.request==='next/link'?'link.js':resource.request==='next/navigation'?'navigation.js':resource.request.endsWith('etoiles-data')?'data.js':'supabase.js')})],
},async(error,stats)=>{
 if(error||stats.hasErrors()){console.error(error||stats.toString({all:false,errors:true}));process.exitCode=1;return}
 const css=await require('postcss')([require('@tailwindcss/postcss')()]).process(fs.readFileSync(path.join(root,'app/globals.css'),'utf8'),{from:path.join(root,'app/globals.css')});fs.writeFileSync(path.join(dir,'style.css'),css.css)
 const html='<!doctype html><html lang="fr" data-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Recette fictive Mes étoiles</title><link rel="stylesheet" href="/style.css"></head><body style="margin:0;font-family:system-ui"><div id="root"></div><script src="/bundle.js"></script></body></html>'
 http.createServer((req,res)=>{const pathname=new URL(req.url,'http://127.0.0.1:3210').pathname,file=['/bundle.js','/style.css'].includes(pathname)?path.join(dir,pathname.slice(1)):null;res.setHeader('Cache-Control','no-store');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Content-Security-Policy',"default-src 'self'; connect-src 'none'; style-src 'self' 'unsafe-inline'; font-src 'self'; img-src 'self' data:");res.setHeader('Content-Type',file?.endsWith('.css')?'text/css':file?.endsWith('.js')?'text/javascript':'text/html; charset=utf-8');res.end(file?fs.readFileSync(file):html)}).listen(3210,'127.0.0.1',()=>console.log('PREVIEW_READY http://127.0.0.1:3210 — aucun accès distant'))
})
