// Navigateur réel, vrais composants/CSS, persistance FICTIVE en mémoire uniquement.
import fs from 'node:fs'
import path from 'node:path'
import http from 'node:http'
import { createRequire } from 'node:module'
const require = createRequire(import.meta.url), root = process.cwd(), dir = path.join(root, 'out/univers-preview')
fs.mkdirSync(dir, { recursive: true })
fs.writeFileSync(path.join(dir, 'loader.cjs'), `const ts=require('typescript');module.exports=source=>ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText`)
fs.writeFileSync(path.join(dir, 'navigation.js'), `export const usePathname=()=>'/dashboard/univers';export const useRouter=()=>({push:()=>{}})`)
fs.writeFileSync(path.join(dir, 'link.js'), `import React from 'react';export default function Link({children,...props}){return React.createElement('a',props,children)}`)
fs.writeFileSync(path.join(dir, 'social.js'), `import React,{createContext,useContext} from 'react';export const PreviewSocial=createContext(null);export const useEtoiles=()=>useContext(PreviewSocial)`)
fs.writeFileSync(path.join(dir, 'avatar.js'), `import React,{createContext,useContext} from 'react';export const PreviewAvatar=createContext(null);export const useDashboardAvatar=()=>useContext(PreviewAvatar)`)
fs.writeFileSync(path.join(dir, 'supabase.js'), `export const supabase={auth:{getSession:async()=>({data:{session:{user:{id:window.fixtureOwner},access_token:'fictitious-jwt'}},error:null})}}`)
fs.writeFileSync(path.join(dir, 'entry.js'), `
import React,{useState} from 'react';import {createRoot} from 'react-dom/client';import UniversScreen from '../../components/univers/UniversScreen';import UniversPartagePanel from '../../components/univers/UniversPartagePanel';import ContactEtoile from '../../components/etoiles/ContactEtoile';import {DashboardUserContext} from '../../components/DashboardUserContext';import {PreviewSocial} from './social';import {PreviewAvatar} from './avatar';import ContactDraftProvider from '../../components/ContactDraftProvider';import {universInitial,monUnivers,apercuUnivers,PARTAGE_UNIVERS_VIDE} from '../../lib/univers-contract';import {DEFAULT_AVATAR_V3} from '../../lib/avatar-collection-v3';
const A='10000000-0000-4000-8000-000000000001',B='10000000-0000-4000-8000-000000000002',R='10000000-0000-4000-8000-000000000003';
const rows=new Map(),operations=new Map(),copy=v=>JSON.parse(JSON.stringify(v));window.previewWrites=[];window.fixtureOnline=true;window.fixtureRelation=true;window.fixtureOwner=A;Object.defineProperty(navigator,'onLine',{get:()=>window.fixtureOnline,configurable:true});
const api={lire:async(owner,signal)=>{if(signal.aborted)throw new Error('Lecture abandonnée');return copy(rows.get(owner)||universInitial(owner===A?'Lune':'Compte B'))},commander:async(owner,command,signal)=>{if(signal.aborted)throw new Error('Écriture abandonnée');window.previewWrites.push(copy(command));if(window.failNext){window.failNext=false;throw new Error('Panne fictive avant écriture')}const key=owner+command.operation;if(!operations.has(key)){let row=rows.get(owner)||universInitial(owner===A?'Lune':'Compte B');if(row.revision!==command.revision)throw new Error('Conflit fictif');row=command.action==='enregistrer'?monUnivers({...command.donnees,revision:row.revision+1}):{...row,revision:row.revision+(row.revision?1:0),partage:{...PARTAGE_UNIVERS_VIDE}};rows.set(owner,copy(row));operations.set(key,{ok:true,revision:row.revision})}if(window.lostNext){window.lostNext=false;throw new Error('Réponse fictive perdue')}return copy(operations.get(key))}};
const friend=universInitial('Polaris');friend.valeurs.passions='Musique et randonnée';friend.partage.passions=true;friend.valeurs.anniversaire={jour:29,mois:2,annee:2000};friend.partage.anniversaire=true;friend.partage.avatar=true;friend.valeurs.eviter='SECRET PRIVE';
window.fetch=async(url,options)=>{const target=new URL(url,location.origin);if(!target.pathname.startsWith('/api/univers')||target.origin!==location.origin)throw new Error('Réseau externe interdit');const signal=options.signal;if(!window.fixtureOnline)throw new Error('Hors ligne fictif');if(target.pathname.endsWith('/etoile'))return Response.json(window.fixtureRelation?apercuUnivers(friend,DEFAULT_AVATAR_V3):{error:'Univers indisponible'},{status:window.fixtureRelation?200:403});try{return Response.json(options.method==='POST'?await api.commander(window.fixtureOwner,JSON.parse(options.body),signal):await api.lire(window.fixtureOwner,signal))}catch(error){return Response.json({error:error.message},{status:409})}};
function App(){const[owner,setOwner]=useState(A),[dark,setDark]=useState(true),[avatar,setAvatar]=useState(copy(DEFAULT_AVATAR_V3)),[online,setOnline]=useState(true),[active,setActive]=useState(true),[associated,setAssociated]=useState(true),[view,setView]=useState('univers');window.fixtureOwner=owner;window.fixtureRelation=active;const social={actives:active?[{id:R,etoile_id:B,identite:'Polaris',origine:'demande'}]:[],associations:associated?[{contact_id:'7',etoile_id:B,relation_id:R}]:[],error:'',offline:!online,loading:false,refresh:async()=>{}};return React.createElement(DashboardUserContext.Provider,{value:{id:owner,email:'fiction@example.invalid'}},React.createElement(PreviewSocial.Provider,{value:social},React.createElement(PreviewAvatar.Provider,{value:{config:avatar,savedConfig:owner===A?avatar:null}},React.createElement(ContactDraftProvider,{key:owner},
React.createElement('nav',{className:'flex flex-wrap items-center gap-2 border-b border-line p-3 text-ink'},React.createElement('p',{className:'w-full text-sm text-muted'},'Aperçu du lot 10B — données fictives en mémoire, aucune sauvegarde dans Ephemer'),
...[
['Mon univers',()=>setView('univers')],['Mes étoiles',()=>setView('etoiles')],['Changer de compte',()=>{setOwner(owner===A?B:A);setView('univers')}],['Thème',()=>{setDark(!dark);document.documentElement.dataset.theme=dark?'light':'dark'}],['Simuler une panne',()=>{window.failNext=true}],['Simuler une réponse perdue',()=>{window.lostNext=true}],['Modifier avatar fictif',()=>setAvatar({...avatar,hairColorId:avatar.hairColorId==='cuivre'?'chataigne':'cuivre'})],['Hors ligne',()=>{window.fixtureOnline=!online;setOnline(!online);window.dispatchEvent(new Event(online?'offline':'online'))}],['Retirer relation fictive',()=>setActive(!active)],['Retirer association fictive',()=>setAssociated(!associated)]
].map(([label,action])=>React.createElement('button',{key:label,className:'min-h-11 rounded-lg border border-line px-3',onClick:action},label))),view==='univers'?React.createElement(UniversScreen):React.createElement('main',{className:'mx-auto max-w-5xl space-y-6 p-4'},React.createElement('h1',{className:'text-2xl font-bold'},'Mes étoiles — simulation'),React.createElement('section',{className:'rounded-2xl border border-line p-4'},React.createElement('h2',null,'Polaris — sans fiche'),React.createElement(UniversPartagePanel,{etoileId:B})),React.createElement('section',{className:'rounded-2xl border border-line p-4'},React.createElement('h2',null,'Fiche privée : Camille'),React.createElement(ContactEtoile,{contactId:'7',email:null}))))))) };createRoot(document.getElementById('root')).render(React.createElement(App));
`)
const webpack = require('next/dist/compiled/webpack/webpack').webpack
webpack({ mode: 'development', entry: path.join(dir, 'entry.js'), output: { path: dir, filename: 'bundle.js' }, resolve: { extensions: ['.tsx', '.ts', '.js'], alias: { '@': root } },
  module: { rules: [{ test: /\.tsx?$/, exclude: /node_modules/, use: path.join(dir, 'loader.cjs') }] }, devtool: false,
  plugins: [new webpack.DefinePlugin({ 'process.env': JSON.stringify({ NODE_ENV: 'development' }) }), new webpack.NormalModuleReplacementPlugin(/^next\/link$|^next\/navigation$|(?:supabase-browser|EtoilesContext|DashboardAvatarContext)$/, resource => { resource.request = path.join(dir, resource.request === 'next/link' ? 'link.js' : resource.request === 'next/navigation' ? 'navigation.js' : resource.request.endsWith('supabase-browser') ? 'supabase.js' : resource.request.endsWith('EtoilesContext') ? 'social.js' : 'avatar.js') })],
}, async (error, stats) => {
  if (error || stats.hasErrors()) { console.error(error || stats.toString({ all: false, errors: true })); process.exitCode = 1; return }
  const css = await require('postcss')([require('@tailwindcss/postcss')()]).process(fs.readFileSync(path.join(root, 'app/globals.css'), 'utf8'), { from: path.join(root, 'app/globals.css') })
  fs.writeFileSync(path.join(dir, 'style.css'), css.css)
  const html = '<!doctype html><html lang="fr" data-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Aperçu fictif Mon univers</title><link rel="stylesheet" href="/style.css"></head><body style="margin:0;font-family:system-ui"><div id="root"></div><script src="/bundle.js"></script></body></html>'
  http.createServer((req, res) => { const pathname = new URL(req.url, 'http://127.0.0.1:3211').pathname, file = ['/bundle.js', '/style.css'].includes(pathname) ? path.join(dir, pathname.slice(1)) : null
    res.setHeader('Cache-Control', 'no-store'); res.setHeader('Referrer-Policy', 'no-referrer'); res.setHeader('Content-Security-Policy', "default-src 'self'; connect-src 'none'; style-src 'self' 'unsafe-inline'; font-src 'self'; img-src 'self' data:")
    res.setHeader('Content-Type', file?.endsWith('.css') ? 'text/css' : file?.endsWith('.js') ? 'text/javascript' : 'text/html; charset=utf-8'); res.end(file ? fs.readFileSync(file) : html)
  }).listen(3211, '127.0.0.1', () => console.log('PREVIEW_READY http://127.0.0.1:3211 — aperçu fictif, réseau interdit'))
})
