// Base de données locale des fêtes des Saints
// Format des dates : "MM-JJ" (mois-jour, sans l'année car la fête tombe chaque année)
// Un prénom principal peut avoir plusieurs VARIANTES qui partagent la même fête

export type Sainte = {
  date: string          // ex: "03-19" pour le 19 mars
  nomSaint: string      // ex: "Saint Joseph" (ce qu'on affichera)
  prenoms: string[]     // liste des prénoms (en minuscules, sans accents)
}

export const SAINTS: Sainte[] = [
  // JANVIER
  { date: "01-01", nomSaint: "Sainte Marie", prenoms: ["marie", "maria", "marion", "mary", "mariam", "marianne", "maryse", "maryline", "marylene"] },
  { date: "01-02", nomSaint: "Saint Basile", prenoms: ["basile", "basil", "basilide"] },
  { date: "01-03", nomSaint: "Sainte Geneviève", prenoms: ["genevieve", "geneveve", "ginette", "ginette"] },
  { date: "01-04", nomSaint: "Saint Odilon", prenoms: ["odilon", "odil", "odile", "odette"] },
  { date: "01-05", nomSaint: "Saint Édouard", prenoms: ["edouard", "edward", "ed", "eddie", "ted", "theodore"] },
  { date: "01-06", nomSaint: "Les Rois Mages", prenoms: ["caspar", "gaspar", "melchior", "balthazar", "epiphane"] },
  { date: "01-07", nomSaint: "Saint Raymond", prenoms: ["raymond", "raimond", "raynard", "renaud"] },
  { date: "01-08", nomSaint: "Saint Lucien", prenoms: ["lucien", "lucie", "lucia", "lucy", "luc", "lucas", "lucien"] },
  { date: "01-09", nomSaint: "Sainte Alix", prenoms: ["alix", "alice", "alicia", "alida", "alida", "alida"] },
  { date: "01-10", nomSaint: "Saint Guillaume", prenoms: ["guillaume", "william", "guillermo", "liam", "will", "willy", "bill", "billy", "guillaume"] },
  { date: "01-11", nomSaint: "Sainte Pauline", prenoms: ["pauline", "paula", "paul", "paulette", "paulina", "paulin", "paule"] },
  { date: "01-12", nomSaint: "Sainte Tatiana", prenoms: ["tatiana", "tania", "tania", "tatiane"] },
  { date: "01-13", nomSaint: "Saint Hilaire", prenoms: ["hilaire", "hilarius", "hilary"] },
  { date: "01-14", nomSaint: "Saint Félix", prenoms: ["felix", "felice", "felicia", "felicity", "felis"] },
  { date: "01-15", nomSaint: "Saint Rémi", prenoms: ["remi", "remy", "remis", "remigius"] },
  { date: "01-16", nomSaint: "Saint Marcel", prenoms: ["marcel", "marcella", "marcelle", "marcelo", "marcellus", "marco", "mark", "marcus"] },
  { date: "01-17", nomSaint: "Saint Antoine", prenoms: ["antoine", "anthony", "antonin", "antonio", "anton", "antonie", "antoinette", "antonia", "antonis"] },
  { date: "01-18", nomSaint: "Sainte Chantal", prenoms: ["chantal", "chantel", "chandal", "chantelle"] },
  { date: "01-19", nomSaint: "Saint Marius", prenoms: ["marius", "mario", "mariano", "marion"] },
  { date: "01-20", nomSaint: "Saint Fabien", prenoms: ["fabien", "fabian", "fabius", "fabrizio", "faber", "fab"] },
  { date: "01-21", nomSaint: "Sainte Agnès", prenoms: ["agnes", "agnes", "ines", "ynes", "ynez", "agnus", "agnese"] },
  { date: "01-22", nomSaint: "Saint Vincent", prenoms: ["vincent", "vincenzo", "vincente", "vince", "vincy"] },
  { date: "01-23", nomSaint: "Saint Bernard", prenoms: ["bernard", "bernardo", "bernardus", "bernie", "berny", "berne"] },
  { date: "01-24", nomSaint: "Saint François de Sales", prenoms: ["francois", "francis", "frank", "frances", "francesca", "francisco", "franz", "franco"] },
  { date: "01-25", nomSaint: "Conversion de Saint Paul", prenoms: ["paul", "paula", "paulette", "pauline", "paulien", "paulin", "paolo", "pablo", "paule"] },
  { date: "01-26", nomSaint: "Sainte Paule", prenoms: ["paule", "paula", "paulette", "pauline", "paulina"] },
  { date: "01-27", nomSaint: "Sainte Angèle", prenoms: ["angele", "angela", "angelique", "angélique", "angelina", "angel", "angle", "anjela"] },
  { date: "01-28", nomSaint: "Saint Thomas d'Aquin", prenoms: ["thomas", "tom", "tommy", "tomasina", "tommaso", "tomas", "tomás", "thoma"] },
  { date: "01-29", nomSaint: "Saint Gédéon", prenoms: ["gedeon", "gideon", "gedeons"] },
  { date: "01-30", nomSaint: "Sainte Martine", prenoms: ["martine", "martin", "marty", "martina", "martino", "marta", "martha", "martinus"] },
  { date: "01-31", nomSaint: "Sainte Marcelle", prenoms: ["marcelle", "marcella", "marcel", "marco", "marcus", "mark"] },

  // FÉVRIER
  { date: "02-01", nomSaint: "Sainte Ella", prenoms: ["ella", "eleanor", "eleonor", "eleonore", "elena", "helen", "helena", "helene"] },
  { date: "02-02", nomSaint: "La Chandeleur", prenoms: ["chandelle"] },
  { date: "02-03", nomSaint: "Saint Blaise", prenoms: ["blaise", "blase", "blaze", "blasius"] },
  { date: "02-04", nomSaint: "Sainte Rosa", prenoms: ["rosa", "rose", "rosette", "rosalia", "rosalie", "rosalinde", "rosalind"] },
  { date: "02-05", nomSaint: "Sainte Agathe", prenoms: ["agathe", "agatha", "agata"] },
  { date: "02-06", nomSaint: "Saint Gaston", prenoms: ["gaston", "gaspard", "gaspar", "gast"] },
  { date: "02-07", nomSaint: "Sainte Eugénie", prenoms: ["eugenie", "eugene", "eugenia", "eugène", "eugen", "evgeny"] },
  { date: "02-08", nomSaint: "Sainte Jacqueline", prenoms: ["jacqueline", "jacqueline", "jacqueline", "jacques", "jacob", "jaco", "jack", "jackie", "jackeline", "jacqueline", "jacqueline"] },
  { date: "02-09", nomSaint: "Sainte Apolline", prenoms: ["apolline", "apollonia", "apoline", "apollone"] },
  { date: "02-10", nomSaint: "Saint Arnaud", prenoms: ["arnaud", "arnold", "arnolt", "arnould", "arnaut"] },
  { date: "02-11", nomSaint: "Notre-Dame de Lourdes", prenoms: ["lourdes", "lourde"] },
  { date: "02-12", nomSaint: "Saint Félix", prenoms: ["felix", "felice", "felicity", "felicia"] },
  { date: "02-13", nomSaint: "Sainte Béatrice", prenoms: ["beatrice", "beatrix", "beatriz", "beatrice", "beatriz"] },
  { date: "02-14", nomSaint: "Saint Valentin", prenoms: ["valentin", "valentine", "valentina", "valentino", "valentin", "valerie", "valentijn"] },
  { date: "02-15", nomSaint: "Saint Claude", prenoms: ["claude", "claudius", "claude", "claudette", "claudine", "claudia", "claudius"] },
  { date: "02-16", nomSaint: "Sainte Julienne", prenoms: ["julienne", "juliana", "julia", "julie", "julian", "julius", "julius", "jules"] },
  { date: "02-17", nomSaint: "Saint Alexis", prenoms: ["alexis", "alex", "alexei", "alexey", "alexius", "alexus"] },
  { date: "02-18", nomSaint: "Sainte Bernadette", prenoms: ["bernadette", "bernard", "bernardine", "bernardo", "bernadine"] },
  { date: "02-19", nomSaint: "Saint Gabin", prenoms: ["gabin", "gabe", "gabriel", "gabrielle", "gabriella", "gabby", "gab"] },
  { date: "02-20", nomSaint: "Sainte Aimée", prenoms: ["aimee", "aimée", "aime"] },
  { date: "02-21", nomSaint: "Saint Damien", prenoms: ["damien", "damian", "damon", "damiano", "damianus", "dame"] },
  { date: "02-22", nomSaint: "Sainte Isabelle", prenoms: ["isabelle", "isabella", "isabela", "isabel", "isabelita", "isa", "belle", "bel", "ibby"] },
  { date: "02-23", nomSaint: "Saint Lazare", prenoms: ["lazare", "lazarus", "lazar", "lazaro", "lazaros"] },
  { date: "02-24", nomSaint: "Saint Mathias", prenoms: ["mathias", "mathieu", "matthias", "matthieu", "matthew", "matteo", "mat", "matt"] },
  { date: "02-25", nomSaint: "Saint Roméo", prenoms: ["romeo", "romeo", "romea"] },
  { date: "02-26", nomSaint: "Saint Modeste", prenoms: ["modeste", "modest", "modestus"] },
  { date: "02-27", nomSaint: "Sainte Honorine", prenoms: ["honorine", "honor", "honoria", "honoree", "honors"] },
  { date: "02-28", nomSaint: "Saint Romain", prenoms: ["romain", "roman", "romano", "romanus", "roma"] },

  // MARS
  { date: "03-01", nomSaint: "Saint Aubin", prenoms: ["aubin", "albin", "albinus", "alban", "alby", "auben"] },
  { date: "03-02", nomSaint: "Saint Simplice", prenoms: ["simplice", "simplicius", "simple"] },
  { date: "03-03", nomSaint: "Sainte Gwladys", prenoms: ["gwladys", "gladys", "glad", "gledys"] },
  { date: "03-04", nomSaint: "Saint Casimir", prenoms: ["casimir", "casimiro", "casey", "cass"] },
  { date: "03-05", nomSaint: "Sainte Olive", prenoms: ["olive", "olivia", "oliver", "olivier", "olivet", "oliva", "olivio", "oliva"] },
  { date: "03-06", nomSaint: "Sainte Colette", prenoms: ["colette", "coletta", "cole", "colet", "cola", "nicolette"] },
  { date: "03-07", nomSaint: "Sainte Félicité", prenoms: ["felicite", "felicity", "felicia", "felice", "felix", "felicity"] },
  { date: "03-08", nomSaint: "Saint Jean de Dieu", prenoms: ["jean", "jean-de-dieu", "john", "jean", "giovanni", "juan", "jeans", "jeanne", "jeanette", "jeanine"] },
  { date: "03-09", nomSaint: "Sainte Françoise", prenoms: ["francoise", "francesca", "frances", "francine", "francie", "fran", "frank", "francis", "francisco"] },
  { date: "03-10", nomSaint: "Saint Vivien", prenoms: ["vivien", "vivienne", "vivian", "viviana", "viv", "vivi"] },
  { date: "03-11", nomSaint: "Sainte Constance", prenoms: ["constance", "constancia", "constant", "constantina", "constantino", "connie", "conny"] },
  { date: "03-12", nomSaint: "Sainte Justine", prenoms: ["justine", "justin", "justina", "justinian", "justus", "jus", "just"] },
  { date: "03-13", nomSaint: "Saint Rodrigue", prenoms: ["rodrigue", "rodrigo", "roderick", "rod", "rodriguez", "rodolphe"] },
  { date: "03-14", nomSaint: "Sainte Mathilde", prenoms: ["mathilde", "mathilda", "matilda", "matilde", "maud", "math", "tilly", "tilda"] },
  { date: "03-15", nomSaint: "Sainte Clémence", prenoms: ["clemence", "clement", "clemency", "clementina", "clementine", "clem", "clemmie", "clemmy"] },
  { date: "03-16", nomSaint: "Saint Bénédict", prenoms: ["benedict", "benoit", "benedikt", "benedicto", "ben", "beni", "benj"] },
  { date: "03-17", nomSaint: "Saint Patrick", prenoms: ["patrick", "patricia", "patrice", "patrick", "patrick", "pat", "patty", "patsy"] },
  { date: "03-18", nomSaint: "Sainte Gabrielle", prenoms: ["gabrielle", "gabriel", "gabriella", "gabriele", "gaby", "gab", "gabby"] },
  { date: "03-19", nomSaint: "Saint Joseph", prenoms: ["joseph", "josephine", "josepha", "jo", "joe", "joey", "josephe", "jody", "joséphine", "josephe"] },
  { date: "03-20", nomSaint: "Saint Cuthbert", prenoms: ["cuthbert", "cuth", "cuthburt"] },
  { date: "03-21", nomSaint: "Sainte Clémence", prenoms: ["clemence", "clement", "clementine", "clementina", "clementino", "clem"] },
  { date: "03-22", nomSaint: "Sainte Léa", prenoms: ["lea", "leah", "leia", "lia", "leanne", "leah"] },
  { date: "03-23", nomSaint: "Sainte Victorine", prenoms: ["victorine", "victoria", "victor", "victoire", "victorio", "vicky", "vic", "victorio"] },
  { date: "03-24", nomSaint: "Sainte Catherine de Suède", prenoms: ["catherine", "catherine", "katerine", "kate", "kathy", "katharyna", "catarina", "catalina", "katrina"] },
  { date: "03-25", nomSaint: "L'Annonciation", prenoms: ["annonciade", "annette", "anna", "ann", "annie", "anna", "anais", "annick", "annoise"] },
  { date: "03-26", nomSaint: "Sainte Larissa", prenoms: ["larissa", "larissa", "larisa", "larisse"] },
  { date: "03-27", nomSaint: "Saint Habib", prenoms: ["habib", "habiba"] },
  { date: "03-28", nomSaint: "Saint Gontran", prenoms: ["gontran", "gontran", "gontrand"] },
  { date: "03-29", nomSaint: "Sainte Gladys", prenoms: ["gladys", "glad", "glady", "gladyse"] },
  { date: "03-30", nomSaint: "Sainte Amelie", prenoms: ["amelie", "amelia", "amala", "emily", "emilia", "emilie", "amélie", "amalya"] },
  { date: "03-31", nomSaint: "Saint Benjamin", prenoms: ["benjamin", "benjamin", "ben", "benji", "benjy", "benny", "benj", "benjamín"] },

  // AVRIL
  { date: "04-01", nomSaint: "Saint Hugues", prenoms: ["hugues", "hugh", "hugo", "hughes", "hugh", "huw"] },
  { date: "04-02", nomSaint: "Saint François de Paule", prenoms: ["francois", "francis", "frank", "francisco", "frank", "franco", "franziska"] },
  { date: "04-03", nomSaint: "Saint Richard", prenoms: ["richard", "ricardo", "rickard", "rich", "richie", "rick", "dick", "riccardo"] },
  { date: "04-04", nomSaint: "Saint Isidore", prenoms: ["isidore", "isidor", "isidoro", "isidro"] },
  { date: "04-05", nomSaint: "Saint Vincent Ferrier", prenoms: ["vincent", "vincenzo", "vincente", "vince", "vincente"] },
  { date: "04-06", nomSaint: "Sainte Marcelline", prenoms: ["marcelline", "marcella", "marcelle", "marcela", "marc", "marcy"] },
  { date: "04-07", nomSaint: "Saint Jean-Baptiste de la Salle", prenoms: ["jean", "jean-baptiste", "john", "giovanni", "juan", "jean", "jean-paul"] },
  { date: "04-08", nomSaint: "Sainte Diotima", prenoms: ["diotima", "dioti"] },
  { date: "04-09", nomSaint: "Saint Gautier", prenoms: ["gautier", "walter", "walt", "walter", "walter"] },
  { date: "04-10", nomSaint: "Saint Ezechiel", prenoms: ["ezechiel", "ezekiel", "ezechias", "ezequiel", "zeke"] },
  { date: "04-11", nomSaint: "Saint Stanislas", prenoms: ["stanislas", "stanislav", "stanislaw", "stanislaus", "stan", "stani"] },
  { date: "04-12", nomSaint: "Saint Jules", prenoms: ["jules", "julius", "julius", "julio", "julian", "julien"] },
  { date: "04-13", nomSaint: "Saint Hermas", prenoms: ["hermas", "herman", "hermanus", "herm"] },
  { date: "04-14", nomSaint: "Saint Tiburcio", prenoms: ["tiburcio", "tiburce"] },
  { date: "04-15", nomSaint: "Sainte Emma", prenoms: ["emma", "emily", "emilia", "emmie", "emmy"] },
  { date: "04-16", nomSaint: "Sainte Bernadine", prenoms: ["bernadine", "bernadette", "bernarda", "bernardina", "bernardo", "bernie"] },
  { date: "04-17", nomSaint: "Saint Anicet", prenoms: ["anicet", "anictetus", "anicetus"] },
  { date: "04-18", nomSaint: "Sainte Parfaite", prenoms: ["parfaite", "parfait", "parfaita"] },
  { date: "04-19", nomSaint: "Saint Léon", prenoms: ["leon", "leona", "leonora", "leonid", "leonardo", "leonel", "leo", "leonard"] },
  { date: "04-20", nomSaint: "Saint Marcien", prenoms: ["marcien", "marcianus", "marcion"] },
  { date: "04-21", nomSaint: "Saint Anselme", prenoms: ["anselme", "anselm", "anselmus", "ansel", "anselmo", "ansell"] },
  { date: "04-22", nomSaint: "Saint Alexandre", prenoms: ["alexandre", "alexander", "alexandra", "alex", "alexander", "sandra", "sandy", "sacha", "sasha", "alexis", "alexandr"] },
  { date: "04-23", nomSaint: "Saint Georges", prenoms: ["georges", "george", "georgina", "georgia", "georgette", "george", "georgina", "jorge", "georg", "georgie"] },
  { date: "04-24", nomSaint: "Sainte Fidèle", prenoms: ["fidele", "fidelis", "fidela"] },
  { date: "04-25", nomSaint: "Saint Marc", prenoms: ["marc", "marcus", "marco", "mark", "marcie", "markel", "marko", "marcus", "marco"] },
  { date: "04-26", nomSaint: "Sainte Alida", prenoms: ["alida", "alide", "alicia", "alice", "alida", "alida"] },
  { date: "04-27", nomSaint: "Saint Zita", prenoms: ["zita", "ziti", "zitella"] },
  { date: "04-28", nomSaint: "Saint Valérien", prenoms: ["valerien", "valerian", "valeriana", "valerie", "val"] },
  { date: "04-29", nomSaint: "Sainte Catherine de Sienne", prenoms: ["catherine", "katerine", "catherine", "cathy", "kate", "kathy", "kathryn", "catharina", "katarina"] },
  { date: "04-30", nomSaint: "Sainte Rose de Lima", prenoms: ["rose", "rosa", "rosalind", "rosalie", "rosalba", "rosy", "rosetta", "rosemary", "rosamund"] },

  // MAI
  { date: "05-01", nomSaint: "Saint Philippe", prenoms: ["philippe", "philip", "philip", "phil", "filip", "phillips", "philip", "phillipe", "philip"] },
  { date: "05-02", nomSaint: "Saint Athanase", prenoms: ["athanase", "athanasius", "athanas"] },
  { date: "05-03", nomSaint: "Sainte Croix", prenoms: ["croix"] },
  { date: "05-04", nomSaint: "Sainte Sylvie", prenoms: ["sylvie", "sylvia", "sylvan", "sylvain", "sylvester", "sylvio", "sylvain", "silvio"] },
  { date: "05-05", nomSaint: "Sainte Judith", prenoms: ["judith", "judita", "judy", "judson"] },
  { date: "05-06", nomSaint: "Sainte Prudence", prenoms: ["prudence", "prudentia", "pru", "prudence"] },
  { date: "05-07", nomSaint: "Saint Gisèle", prenoms: ["gisele", "giselle", "gisela", "gizelle", "giselda"] },
  { date: "05-08", nomSaint: "Saint Apparition de Michel", prenoms: ["michel", "michael", "micheline", "michela", "michaella", "mike", "mick", "micha", "michail"] },
  { date: "05-09", nomSaint: "Sainte Beatrice", prenoms: ["beatrice", "beatrix", "beatrice", "beatrice", "beatrice"] },
  { date: "05-10", nomSaint: "Saint Antonin", prenoms: ["antonin", "antoninus", "antonino", "anton", "antonie", "antonio"] },
  { date: "05-11", nomSaint: "Sainte Estelle", prenoms: ["estelle", "estela", "stella", "estelle", "ester", "estrella"] },
  { date: "05-12", nomSaint: "Sainte Nérée", prenoms: ["neree", "nereus", "nerea"] },
  { date: "05-13", nomSaint: "Sainte Rolande", prenoms: ["rolande", "roland", "rolando", "rolanda", "rolands"] },
  { date: "05-14", nomSaint: "Sainte Matthie", prenoms: ["matthie", "matthias", "mathieu", "matthew", "matthaeus", "matt", "matteo"] },
  { date: "05-15", nomSaint: "Sainte Denise", prenoms: ["denise", "denis", "denice", "dennis", "denys", "dennis", "denny", "denese"] },
  { date: "05-16", nomSaint: "Saint Honoré", prenoms: ["honore", "honor", "honoria", "honorius", "honors", "honore", "honour"] },
  { date: "05-17", nomSaint: "Sainte Pascale", prenoms: ["pascale", "pascal", "pascaline", "pascala", "pascalis", "pascal", "pasquale"] },
  { date: "05-18", nomSaint: "Sainte Éric", prenoms: ["eric", "erica", "erika", "erick", "erik", "eric", "erik"] },
  { date: "05-19", nomSaint: "Saint Yves", prenoms: ["yves", "ivo", "ives", "ivo", "ivor"] },
  { date: "05-20", nomSaint: "Saint Bernardin", prenoms: ["bernardin", "bernardino", "bernard", "bernardo", "bernie"] },
  { date: "05-21", nomSaint: "Saint Denys", prenoms: ["denys", "dennis", "denis", "denys", "denice", "deneese"] },
  { date: "05-22", nomSaint: "Sainte Emilie", prenoms: ["emilie", "emily", "emilia", "emely", "émilie", "emilia"] },
  { date: "05-23", nomSaint: "Saint Didier", prenoms: ["didier", "didium", "didius"] },
  { date: "05-24", nomSaint: "Sainte Suzanne", prenoms: ["suzanne", "susanna", "susan", "suzann", "sue", "suzy", "suzie", "susie", "susannah"] },
  { date: "05-25", nomSaint: "Sainte Magdalena", prenoms: ["magdalena", "magdalene", "madeleine", "magdalen", "magda", "mag", "maggie", "maud"] },
  { date: "05-26", nomSaint: "Saint Philippe Néri", prenoms: ["philippe", "philip", "phil", "filippo", "phillips"] },
  { date: "05-27", nomSaint: "Saint Augustin", prenoms: ["augustin", "augustine", "augusto", "august", "augustine", "augusto", "austen", "austin", "gus", "gussy"] },
  { date: "05-28", nomSaint: "Saint Germain", prenoms: ["germain", "german", "germaine", "germano", "germanus", "germ"] },
  { date: "05-29", nomSaint: "Sainte Jeanne", prenoms: ["jeanne", "jean", "jane", "jane", "jeanette", "jeanine", "jeannette", "jeanne", "joan", "joanna", "joanne"] },
  { date: "05-30", nomSaint: "Sainte Jeanne d'Arc", prenoms: ["jeanne", "jean", "jane", "joan", "joanna", "joanne", "jeannette", "jeanette", "jeanine"] },
  { date: "05-31", nomSaint: "Sainte Pétronille", prenoms: ["petronille", "petronella", "petrona"] },

  // JUIN
  { date: "06-01", nomSaint: "Saint Justin", prenoms: ["justin", "justine", "justina", "justus", "justinian"] },
  { date: "06-02", nomSaint: "Saint Martial", prenoms: ["martial", "martiale", "martialis", "marty", "mart"] },
  { date: "06-03", nomSaint: "Saint Kévin", prenoms: ["kevin", "kevyn", "kev"] },
  { date: "06-04", nomSaint: "Saint Quentin", prenoms: ["quentin", "quenten", "quentin", "quin", "quentin"] },
  { date: "06-05", nomSaint: "Saint Boniface", prenoms: ["boniface", "bonifacio", "bonifatius", "bonifazio"] },
  { date: "06-06", nomSaint: "Saint Norbert", prenoms: ["norbert", "norberto", "norbertus", "norby", "norb"] },
  { date: "06-07", nomSaint: "Saint Robert", prenoms: ["robert", "roberto", "roberta", "robert", "rob", "bobby", "robbie", "bert", "berty", "bert"] },
  { date: "06-08", nomSaint: "Saint Medard", prenoms: ["medard", "medardus"] },
  { date: "06-09", nomSaint: "Sainte Colette", prenoms: ["colette", "coletta", "cole", "coletta", "cola"] },
  { date: "06-10", nomSaint: "Sainte Marguerite", prenoms: ["marguerite", "margaret", "margery", "margot", "marge", "maggie", "peggy", "margarita", "margherita"] },
  { date: "06-11", nomSaint: "Saint Barnabé", prenoms: ["barnabe", "barnabas", "barnabus", "barny", "barn"] },
  { date: "06-12", nomSaint: "Saint Léon", prenoms: ["leon", "leonard", "leona", "leonora", "leo", "leon", "leonida"] },
  { date: "06-13", nomSaint: "Saint Antoine de Padoue", prenoms: ["antoine", "anthony", "antonio", "anton", "antonin", "antonie", "antoinette", "antonia"] },
  { date: "06-14", nomSaint: "Sainte Élisabeth", prenoms: ["elisabeth", "elizabeth", "elisabetta", "elizabeth", "betsy", "beth", "liz", "lizzie", "lisette", "elsa", "isabelle"] },
  { date: "06-15", nomSaint: "Saint Vit", prenoms: ["vit", "vitus", "vita"] },
  { date: "06-16", nomSaint: "Saint Jean-François Régis", prenoms: ["jean", "jean-francois", "john", "francois", "frank", "jean-paul"] },
  { date: "06-17", nomSaint: "Saint Hervé", prenoms: ["herve", "hervey", "hervey", "hervey"] },
  { date: "06-18", nomSaint: "Sainte Léonie", prenoms: ["leonie", "leonia", "leone", "leo", "leonida"] },
  { date: "06-19", nomSaint: "Saint Gervais", prenoms: ["gervais", "gervasio", "gervasy", "gervas"] },
  { date: "06-20", nomSaint: "Saint Silvère", prenoms: ["silvere", "silverius", "silvério"] },
  { date: "06-21", nomSaint: "Saint Louis", prenoms: ["louis", "louise", "lou", "loulou", "louisa", "louison", "luis", "ludovic", "ludovic"] },
  { date: "06-22", nomSaint: "Saint Alban", prenoms: ["alban", "alben", "alba", "albo", "albinus"] },
  { date: "06-23", nomSaint: "Saint Joseph Cafasso", prenoms: ["joseph", "josephine", "jo", "joe", "joey", "josephe"] },
  { date: "06-24", nomSaint: "Saint Jean-Baptiste", prenoms: ["jean", "jean-baptiste", "john", "giovanni", "juan", "jean", "jan", "jean-paul", "john"] },
  { date: "06-25", nomSaint: "Sainte Léopoldine", prenoms: ["leopoldine", "leopoldina", "leopold", "leopoldus"] },
  { date: "06-26", nomSaint: "Saint Josaphat", prenoms: ["josaphat", "joseph", "josafat"] },
  { date: "06-27", nomSaint: "Sainte Fernande", prenoms: ["fernande", "fernando", "fernand", "fernando", "fern", "nando"] },
  { date: "06-28", nomSaint: "Saint Irénée", prenoms: ["irenee", "irene", "irenaeus", "irina", "irena"] },
  { date: "06-29", nomSaint: "Saint Pierre et Paul", prenoms: ["pierre", "peter", "peter", "pete", "pedro", "piero", "pier", "perrin", "paul", "paula", "paulette", "pauline", "paulin", "paulo", "pablo"] },
  { date: "06-30", nomSaint: "Saint Paul", prenoms: ["paul", "paula", "paulette", "pauline", "paulien", "paulin", "pablo", "paolo", "paulo"] },

  // JUILLET
  { date: "07-01", nomSaint: "Saint Thierry", prenoms: ["thierry", "terry", "terence", "therese", "theresa", "teresa"] },
  { date: "07-02", nomSaint: "Sainte Mariette", prenoms: ["mariette", "marie", "mary", "maria", "marion", "marienne"] },
  { date: "07-03", nomSaint: "Saint Thomas", prenoms: ["thomas", "tom", "tommy", "tomás", "tomas", "tomasina", "tommaso", "thoma"] },
  { date: "07-04", nomSaint: "Saint Florent", prenoms: ["florent", "florentina", "florentine", "florentius", "flo", "flory"] },
  { date: "07-05", nomSaint: "Saint Anthelme", prenoms: ["anthelme", "antelm", "antheim"] },
  { date: "07-06", nomSaint: "Sainte Mariette", prenoms: ["mariette", "marie", "mary", "maria", "marian", "mariam", "marienne"] },
  { date: "07-07", nomSaint: "Saint Raoul", prenoms: ["raoul", "ralph", "raul", "ralf", "raule"] },
  { date: "07-08", nomSaint: "Saint Thibault", prenoms: ["thibault", "thibaut", "thibold", "thibaut", "theobald", "theobald", "theo", "thibault"] },
  { date: "07-09", nomSaint: "Sainte Amandine", prenoms: ["amandine", "amanda", "amandus", "amanda", "mandy", "amanda"] },
  { date: "07-10", nomSaint: "Saint Ulric", prenoms: ["ulric", "ulrich", "ulricus", "ulrique", "ulrika"] },
  { date: "07-11", nomSaint: "Saint Benoît", prenoms: ["benoit", "benedict", "ben", "beni", "benj", "benedikt", "benedicto"] },
  { date: "07-12", nomSaint: "Sainte Véronique", prenoms: ["veronique", "veronica", "veron", "ronique"] },
  { date: "07-13", nomSaint: "Saint Henri", prenoms: ["henri", "henry", "henry", "henry", "harry", "heinrich", "enrique", "hank", "hal"] },
  { date: "07-14", nomSaint: "Sainte Camille", prenoms: ["camille", "camilla", "camila", "cam", "camille"] },
  { date: "07-15", nomSaint: "Saint Donald", prenoms: ["donald", "donaldo", "donald", "don", "donnie"] },
  { date: "07-16", nomSaint: "Sainte Carmela", prenoms: ["carmela", "carmela", "carmel", "carmelo", "carmelita"] },
  { date: "07-17", nomSaint: "Saint Alexis", prenoms: ["alexis", "alexei", "alexey", "alex", "alexius", "alexus"] },
  { date: "07-18", nomSaint: "Saint Camille", prenoms: ["camille", "camilla", "camila", "cam"] },
  { date: "07-19", nomSaint: "Saint Vincent de Paul", prenoms: ["vincent", "vincenzo", "vincente", "vince", "vincy", "paul", "paula", "paulette"] },
  { date: "07-20", nomSaint: "Sainte Marguerite", prenoms: ["marguerite", "margaret", "margery", "margot", "marge", "maggie", "peggy", "margarita"] },
  { date: "07-21", nomSaint: "Saint Victor", prenoms: ["victor", "victoria", "vittorio", "vittore", "vic", "vicky", "vittorino"] },
  { date: "07-22", nomSaint: "Sainte Madeleine", prenoms: ["madeleine", "magdalena", "magdalene", "magdalen", "magda", "mag", "maggie", "maud", "maddy", "maddie"] },
  { date: "07-23", nomSaint: "Sainte Brigitte", prenoms: ["brigitte", "bridget", "brigid", "bridgette", "brigitta", "briget", "brig", "birdie"] },
  { date: "07-24", nomSaint: "Sainte Christine", prenoms: ["christine", "christina", "christine", "cristina", "christine", "christy", "chris", "christie", "christelle", "christiane"] },
  { date: "07-25", nomSaint: "Saint Jacques", prenoms: ["jacques", "jacob", "james", "jaco", "jack", "jim", "jimmy", "james", "jacob", "jacoby"] },
  { date: "07-26", nomSaint: "Sainte Anne", prenoms: ["anne", "anna", "annie", "annette", "annick", "anneline", "annabel"] },
  { date: "07-27", nomSaint: "Sainte Natalie", prenoms: ["natalie", "natalia", "natalya", "natalie", "nat", "nataly", "natasja", "natascha"] },
  { date: "07-28", nomSaint: "Saint Samson", prenoms: ["samson", "samson", "sammy", "sam"] },
  { date: "07-29", nomSaint: "Sainte Marthe", prenoms: ["marthe", "martha", "marta", "mart", "martje", "marte"] },
  { date: "07-30", nomSaint: "Saint Julien", prenoms: ["julien", "julian", "julius", "julio", "julius", "jules", "juliana", "julia", "julie"] },
  { date: "07-31", nomSaint: "Saint Ignace", prenoms: ["ignace", "ignatius", "ignacio", "inacio", "ignacy"] },

  // AOÛT
  { date: "08-01", nomSaint: "Saint Pierre-aux-Liens", prenoms: ["pierre", "peter", "pedro", "piero", "pier", "perrin", "perron"] },
  { date: "08-02", nomSaint: "Saint Eusèbe", prenoms: ["eusebe", "eusebius", "eusebio"] },
  { date: "08-03", nomSaint: "Saint Etienne", prenoms: ["etienne", "stephen", "stephanie", "stephane", "steve", "stefan", "stephen", "stefan", "esteve"] },
  { date: "08-04", nomSaint: "Saint Dominique", prenoms: ["dominique", "dominic", "dominica", "domenico", "dominico", "domenic", "dom", "dommy", "dominik"] },
  { date: "08-05", nomSaint: "Notre-Dame Apparition", prenoms: ["marie", "mary", "maria"] },
  { date: "08-06", nomSaint: "Saint Gaëtan", prenoms: ["gaetan", "gaetano", "gaétan", "gaetanus"] },
  { date: "08-07", nomSaint: "Saint Jean Vianney", prenoms: ["jean", "john", "giovanni", "juan", "jean", "jean-paul"] },
  { date: "08-08", nomSaint: "Sainte Irène", prenoms: ["irene", "irenee", "irina", "irena", "irenaeus"] },
  { date: "08-09", nomSaint: "Saint Édith", prenoms: ["edith", "editha", "edie", "eddy"] },
  { date: "08-10", nomSaint: "Saint Laurent", prenoms: ["laurent", "lawrence", "larry", "laurence", "laurentius", "lawrence", "laure", "laurence", "lorenz", "lorenzo"] },
  { date: "08-11", nomSaint: "Sainte Claire", prenoms: ["claire", "clara", "clara", "clarisse", "clara", "clarice", "clarissa", "clara", "clare", "claire"] },
  { date: "08-12", nomSaint: "Sainte Phoebe", prenoms: ["phoebe", "phebe", "febe", "phoebé"] },
  { date: "08-13", nomSaint: "Saint Hippolyte", prenoms: ["hippolyte", "hippolytus", "hippolito"] },
  { date: "08-14", nomSaint: "Assomption Veille", prenoms: ["assomption"] },
  { date: "08-15", nomSaint: "Assomption de Marie", prenoms: ["marie", "mary", "maria", "marian", "mariam", "marianne", "marielle", "marienne"] },
  { date: "08-16", nomSaint: "Saint Roch", prenoms: ["roch", "rocco", "rochus", "rochelle"] },
  { date: "08-17", nomSaint: "Saint Hyacinthe", prenoms: ["hyacinthe", "hyacinth", "hyacinthus", "jacinto", "hyacinthus"] },
  { date: "08-18", nomSaint: "Sainte Hélène", prenoms: ["helene", "helen", "helena", "ella", "eleanor", "eleonor", "eleonore", "elena"] },
  { date: "08-19", nomSaint: "Sainte Jeanne Chantal", prenoms: ["jeanne", "jean", "jane", "jeanette", "jeannette", "chantal", "chantel"] },
  { date: "08-20", nomSaint: "Saint Bernard", prenoms: ["bernard", "bernardus", "bernardino", "bernardo", "bernie", "barny", "bern"] },
  { date: "08-21", nomSaint: "Sainte Christiane", prenoms: ["christiane", "christine", "christina", "christine", "christy", "christie", "chris", "christelle"] },
  { date: "08-22", nomSaint: "Sainte Fabienne", prenoms: ["fabienne", "fabian", "fabiano", "fabio", "fab", "fabiola"] },
  { date: "08-23", nomSaint: "Saint Louis", prenoms: ["louis", "louise", "lou", "loulou", "louisa", "louison", "luis", "ludovic"] },
  { date: "08-24", nomSaint: "Saint Barthélemy", prenoms: ["barthelemy", "bartholomew", "barth", "bart", "bartley", "bartolomé", "bartolo"] },
  { date: "08-25", nomSaint: "Saint Louis", prenoms: ["louis", "louise", "lou", "loulou", "louisa", "louison", "luis", "ludovic"] },
  { date: "08-26", nomSaint: "Saint Nathalie", prenoms: ["nathalie", "natalia", "natalie", "nat", "nataly", "natasja", "natascha"] },
  { date: "08-27", nomSaint: "Sainte Monique", prenoms: ["monique", "monika", "monica", "monique"] },
  { date: "08-28", nomSaint: "Saint Augustin", prenoms: ["augustin", "augustine", "augusto", "august", "augustus", "austin", "gus", "gussy", "austen"] },
  { date: "08-29", nomSaint: "Martyre de Saint Jean", prenoms: ["jean", "john", "giovanni", "juan", "jean", "jan", "jean-paul"] },
  { date: "08-30", nomSaint: "Sainte Rose", prenoms: ["rose", "rosa", "rosalie", "rosalba", "rosy", "rosetta", "rosemary", "rosamund", "roselle"] },
  { date: "08-31", nomSaint: "Saint Aristide", prenoms: ["aristide", "aristides"] },

  // SEPTEMBRE
  { date: "09-01", nomSaint: "Saint Gilles", prenoms: ["gilles", "giles", "gilo", "gilberto", "gilberte"] },
  { date: "09-02", nomSaint: "Saint Ingrid", prenoms: ["ingrid", "ingrida", "ingra"] },
  { date: "09-03", nomSaint: "Saint Grégoire", prenoms: ["gregoire", "gregory", "gregorio", "gregorius", "greg", "gregg"] },
  { date: "09-04", nomSaint: "Sainte Rosalie", prenoms: ["rosalie", "rosalia", "rosa", "rose", "rosely", "rosie", "rosalind"] },
  { date: "09-05", nomSaint: "Saint Léonce", prenoms: ["leonce", "leontius", "leone", "leo"] },
  { date: "09-06", nomSaint: "Saint Zacharie", prenoms: ["zacharie", "zacharias", "zachary", "zach", "zeke"] },
  { date: "09-07", nomSaint: "Sainte Reine", prenoms: ["reine", "regina", "reina", "rene", "reinah"] },
  { date: "09-08", nomSaint: "Nativité de Marie", prenoms: ["marie", "mary", "maria", "marian", "mariam", "marienne", "marianne"] },
  { date: "09-09", nomSaint: "Saint Pierre Claver", prenoms: ["pierre", "peter", "pedro", "piero", "pier"] },
  { date: "09-10", nomSaint: "Saint Nicolas de Tolentin", prenoms: ["nicolas", "nicholas", "nicola", "nicole", "nick", "nico", "nicolette"] },
  { date: "09-11", nomSaint: "Sainte Thérèse", prenoms: ["therese", "theresa", "teresa", "thérèse", "theresia", "terri", "tess", "tereza"] },
  { date: "09-12", nomSaint: "Saint Apollinaire", prenoms: ["apollinaire", "apollonius", "apolline", "apollone"] },
  { date: "09-13", nomSaint: "Sainte Roxane", prenoms: ["roxane", "roxana", "roxanna", "roxie", "roxy"] },
  { date: "09-14", nomSaint: "Sainte Croix Glorieuse", prenoms: ["croix"] },
  { date: "09-15", nomSaint: "Notre-Dame Douleurs", prenoms: ["marie", "mary", "maria", "marian"] },
  { date: "09-16", nomSaint: "Saint Cornélie", prenoms: ["cornelie", "cornelius", "cornell", "cornelia", "cornélie"] },
  { date: "09-17", nomSaint: "Saint Lambert", prenoms: ["lambert", "lambertus", "lambert", "lampert"] },
  { date: "09-18", nomSaint: "Saint Juste", prenoms: ["juste", "justus", "justine", "justin"] },
  { date: "09-19", nomSaint: "Saint Janssen", prenoms: ["janssen"] },
  { date: "09-20", nomSaint: "Sainte Jeanne Hinton", prenoms: ["jeanne", "jean", "jane", "jeanette"] },
  { date: "09-21", nomSaint: "Saint Matthieu", prenoms: ["matthieu", "matthew", "mathieu", "matt", "matteo", "matthaeus", "matthias", "matthew"] },
  { date: "09-22", nomSaint: "Saint Maurice", prenoms: ["maurice", "maurizio", "maurice", "mauritius", "mo", "mort", "morrie", "maurits", "morey"] },
  { date: "09-23", nomSaint: "Saint Thècle", prenoms: ["thecle", "thecla", "thecle"] },
  { date: "09-24", nomSaint: "Saint Gérard", prenoms: ["gerard", "gerald", "geraldine", "gerardo", "gerardus", "gerard", "gerry", "ger", "gerard", "gérard"] },
  { date: "09-25", nomSaint: "Sainte Héritée", prenoms: ["heritee"] },
  { date: "09-26", nomSaint: "Saint Côme", prenoms: ["come", "cosmo", "cosmas", "cosme"] },
  { date: "09-27", nomSaint: "Saint Vincent de Paul", prenoms: ["vincent", "vincenzo", "vincente", "vince"] },
  { date: "09-28", nomSaint: "Saint Wenceslas", prenoms: ["wenceslas", "wenceslaus", "venceslav", "wenceslao"] },
  { date: "09-29", nomSaint: "Saint Michel", prenoms: ["michel", "michael", "michael", "michaella", "michela", "mike", "mick", "micha", "michail", "michela", "michelina"] },
  { date: "09-30", nomSaint: "Saint Jérôme", prenoms: ["jerome", "jeremiah", "jeremias", "jerome", "jerald", "jerry", "jer"] },

  // OCTOBRE
  { date: "10-01", nomSaint: "Saint Rémi", prenoms: ["remi", "remy", "remis", "remigius"] },
  { date: "10-02", nomSaint: "Sainte Léonie", prenoms: ["leonie", "leonia", "leone", "leo", "leonida"] },
  { date: "10-03", nomSaint: "Saint Gérard", prenoms: ["gerard", "gerald", "geraldine", "gerardo", "gerry", "ger"] },
  { date: "10-04", nomSaint: "Saint François d'Assise", prenoms: ["francois", "francis", "frank", "francisco", "francesco", "franco", "frankie", "franz"] },
  { date: "10-05", nomSaint: "Saint Plâcide", prenoms: ["placide", "placidus", "placida"] },
  { date: "10-06", nomSaint: "Sainte Thérèse", prenoms: ["therese", "theresa", "teresa", "thérèse", "terri", "tess"] },
  { date: "10-07", nomSaint: "Notre-Dame du Rosaire", prenoms: ["marie", "rosaire"] },
  { date: "10-08", nomSaint: "Saint Pélagie", prenoms: ["pelagie", "pelagia", "pelagius"] },
  { date: "10-09", nomSaint: "Saint Denis", prenoms: ["denis", "dennis", "denys", "denise", "deneese", "dennie", "denny"] },
  { date: "10-10", nomSaint: "Saint Paulin", prenoms: ["paulin", "paulinus", "pauline", "paul", "paula", "paulette"] },
  { date: "10-11", nomSaint: "Sainte Solange", prenoms: ["solange", "solania"] },
  { date: "10-12", nomSaint: "Saint Séraphin", prenoms: ["seraphin", "seraphinus", "seraphim", "seraphina", "seraphine"] },
  { date: "10-13", nomSaint: "Sainte Thérèse", prenoms: ["therese", "theresa", "teresa", "thérèse"] },
  { date: "10-14", nomSaint: "Saint Juste", prenoms: ["juste", "justus", "justine"] },
  { date: "10-15", nomSaint: "Sainte Thérèse d'Avila", prenoms: ["therese", "theresa", "teresa", "terri", "tess", "tessa"] },
  { date: "10-16", nomSaint: "Sainte Hédwige", prenoms: ["hedwige", "hedwig", "hedwiges", "hadwig"] },
  { date: "10-17", nomSaint: "Saint Ignace", prenoms: ["ignace", "ignatius", "ignacio", "ignacy"] },
  { date: "10-18", nomSaint: "Saint Luc", prenoms: ["luc", "lucas", "luke", "lucus"] },
  { date: "10-19", nomSaint: "Sainte Jeanne-Elisabeth", prenoms: ["jeanne", "jean", "jane", "elizabeth"] },
  { date: "10-20", nomSaint: "Sainte Irène", prenoms: ["irene", "irenee", "irina", "irena"] },
  { date: "10-21", nomSaint: "Sainte Céleste", prenoms: ["celeste", "celestine", "celestina", "celestino"] },
  { date: "10-22", nomSaint: "Sainte Salomé", prenoms: ["salome", "saloma", "salomi"] },
  { date: "10-23", nomSaint: "Saint Jean de Capistran", prenoms: ["jean", "john", "giovanni"] },
  { date: "10-24", nomSaint: "Saint Florentin", prenoms: ["florentin", "florentius", "florentia", "florentine"] },
  { date: "10-25", nomSaint: "Sainte Thérèse", prenoms: ["therese", "theresa", "teresa", "thérèse"] },
  { date: "10-26", nomSaint: "Saint Dimitri", prenoms: ["dimitri", "dimitrius", "dmitri", "dmitriy", "demétrius"] },
  { date: "10-27", nomSaint: "Sainte Victoire", prenoms: ["victoire", "victoria", "victor", "victorio", "vicky", "vic"] },
  { date: "10-28", nomSaint: "Saint Simon", prenoms: ["simon", "simone", "simo", "simeon", "simone", "simeon"] },
  { date: "10-29", nomSaint: "Sainte Narcisse", prenoms: ["narcisse", "narcissus", "narcisa"] },
  { date: "10-30", nomSaint: "Saint Alphonse", prenoms: ["alphonse", "alphonso", "alphonsus", "alphonsia", "alfonse"] },
  { date: "10-31", nomSaint: "Sainte Quitterie", prenoms: ["quitterie", "quitteria"] },

  // NOVEMBRE
  { date: "11-01", nomSaint: "Toussaint", prenoms: ["toussaint", "all", "saints"] },
  { date: "11-02", nomSaint: "Défunts", prenoms: ["defunts", "deceased"] },
  { date: "11-03", nomSaint: "Saint Hubert", prenoms: ["hubert", "huberts", "hubertus", "huberto"] },
  { date: "11-04", nomSaint: "Sainte Amande", prenoms: ["amande", "amanda", "amandus", "amanda", "mandy"] },
  { date: "11-05", nomSaint: "Saint Sylvestre", prenoms: ["sylvestre", "sylvain", "sylvio", "sylvia", "sylvie", "silvio"] },
  { date: "11-06", nomSaint: "Sainte Léonarde", prenoms: ["leonarde", "leonard", "leona", "leonora", "leo"] },
  { date: "11-07", nomSaint: "Sainte Carine", prenoms: ["carine", "carina", "karina", "karen"] },
  { date: "11-08", nomSaint: "Sainte Alix", prenoms: ["alix", "alice", "alicia", "alida"] },
  { date: "11-09", nomSaint: "Saint Théodore", prenoms: ["theodore", "theo", "theodore", "theodor", "theodora", "theodore"] },
  { date: "11-10", nomSaint: "Saint Léon", prenoms: ["leon", "leonard", "leona", "leo", "leonid", "leonardo", "leonel"] },
  { date: "11-11", nomSaint: "Saint Martin", prenoms: ["martin", "martine", "martina", "marty", "mart", "martino", "marte", "martins"] },
  { date: "11-12", nomSaint: "Saint Nonce", prenoms: ["nonce"] },
  { date: "11-13", nomSaint: "Sainte Brice", prenoms: ["brice", "bryce", "bricius"] },
  { date: "11-14", nomSaint: "Sainte Sidonie", prenoms: ["sidonie", "sidonia", "sidonius", "sid", "siddy"] },
  { date: "11-15", nomSaint: "Saint Albert", prenoms: ["albert", "alberta", "albertina", "albertus", "alb", "bert", "berty", "albrecht"] },
  { date: "11-16", nomSaint: "Sainte Marguerite", prenoms: ["marguerite", "margaret", "margery", "margot", "marge", "maggie", "peggy"] },
  { date: "11-17", nomSaint: "Saint Élisée", prenoms: ["elisee", "elisha", "elissa"] },
  { date: "11-18", nomSaint: "Sainte Ève", prenoms: ["eve", "eva", "evelyn", "evelyn", "eveline"] },
  { date: "11-19", nomSaint: "Saint Tanguy", prenoms: ["tanguy", "tanguy", "tancred"] },
  { date: "11-20", nomSaint: "Sainte Edith", prenoms: ["edith", "editha", "edie", "eddy"] },
  { date: "11-21", nomSaint: "Présentation de Marie", prenoms: ["marie", "mary", "maria", "marian"] },
  { date: "11-22", nomSaint: "Sainte Cécile", prenoms: ["cecile", "cecilia", "cecily", "cécile", "celia", "celeya"] },
  { date: "11-23", nomSaint: "Saint Clément", prenoms: ["clement", "clementina", "clementine", "clem", "clemmie"] },
  { date: "11-24", nomSaint: "Sainte Chantal", prenoms: ["chantal", "chantel", "chandal", "chantelle"] },
  { date: "11-25", nomSaint: "Sainte Catherine", prenoms: ["catherine", "katerine", "kate", "kathy", "katharyna", "catarina", "catalina", "katrina", "katharine"] },
  { date: "11-26", nomSaint: "Saint Léonard", prenoms: ["leonard", "leonardo", "leonardo", "leonard", "leonardi", "leo", "lenny", "leonhard"] },
  { date: "11-27", nomSaint: "Saint Maxime", prenoms: ["maxime", "maximus", "max", "maximo", "maximillian", "maximilian"] },
  { date: "11-28", nomSaint: "Saint Jacques", prenoms: ["jacques", "jacob", "james", "jaco", "jack", "jim", "jimmy"] },
  { date: "11-29", nomSaint: "Sainte Saturnine", prenoms: ["saturnine", "saturninus", "saturnina"] },
  { date: "11-30", nomSaint: "Saint André", prenoms: ["andre", "andrew", "andrew", "andrew", "andrew", "andy"]},

  // DÉCEMBRE
  { date: "12-04", nomSaint: "Sainte Barbara", prenoms: ["barbara", "barbe", "babeth"] },
  { date: "12-06", nomSaint: "Saint Nicolas", prenoms: ["nicolas", "nicole", "nicolette", "nico", "nick"] },
  { date: "12-13", nomSaint: "Sainte Lucie", prenoms: ["lucie", "lucia", "lucy", "luce"] },
  { date: "12-25", nomSaint: "Noël", prenoms: ["noel", "noelle", "noella"] },
  { date: "12-26", nomSaint: "Saint Étienne", prenoms: ["etienne", "stephane", "stephanie", "steve", "stefan"] },
  { date: "12-31", nomSaint: "Saint Sylvestre", prenoms: ["sylvestre", "sylvain", "sylvie", "sylvia"] },
]

